### ISSUE TITLE
A question after reading the ROD paper

### ISSUE THREAD

**Issue by LIUkhan** [zwt233/ROD#1]
Hi, wentao! In your paper, multiple similarity matrices for different hops, i.e. Sk,Pk(k=1,2,3...) ,should be calculated and used in different purpose. What confuses me is that when you use the dataset with a big amount of nodes,  the requirement of gpu memory for multiple similarity matrices will explode and it seems unaffordable.  Like the Coauthor Physics with 34493 nodes,  the size of a similarity matrix is 34493 x 34493...

**Comment by zwt233** [comment]
A good question! For extremely large graphs, i.e., graphs of 1,000,000 nodes, one single 𝑆_𝑘 requires more than 931GB memory space, which is not acceptable even for CPU memory. Fortunately, the training process can be done in a mini-batch manner, which supports training on extremely large graphs. More concretely, for large graph, we carry out further approximation that successively takes 𝒎 rows of the 𝑵×𝑵 similarity matrix for ⌈𝑵/𝒎⌉ times and selects 𝑘_1∗𝑚/𝑁 and 𝑘_2∗𝑚/𝑁 positive and negative samples from the 𝑚×𝑁 matrix, supposing 𝑘_1 and 𝑘_2 positive and negative examples need to be selected in total.

**Comment by zwt233** [comment]
> Hi, wentao! In your paper, multiple similarity matrices for different hops, i.e. Sk,Pk(k=1,2,3...) ,should be calculated and used in different purpose. What confuses me is that when you use the dataset with a big amount of nodes, the requirement of gpu memory for multiple similarity matrices will explode and it seems unaffordable. Like the Coauthor Physics with 34493 nodes, the size of a similarity matrix is 34493 x 34493...

A good question! 
1) As we introduced in **_Section 3.2_**, we can view the 𝑁×𝑁 similarity matrix as an array composed of 𝑵^𝟐 elements. We select the most confident and the most unconfident elements in 𝑆_𝑘 as positive examples and negative examples, respectively. Thus, the training process can be done in a mini-batch manner, which supports training on large graphs.

2) For extremely large graphs, i.e., graphs of 1,000,000 nodes, one single 𝑆_𝑘 requires more than 931GB memory space, which is not acceptable even for CPU memory.  We carry out further approximation that successively takes 𝒎 rows of the 𝑵×𝑵 similarity matrix for ⌈𝑵/𝒎⌉ times and selects 𝑘_1∗𝑚/𝑁 and 𝑘_2∗𝑚/𝑁 positive and negative samples from the 𝑚×𝑁 matrix, supposing 𝑘_1 and 𝑘_2 positive and negative examples need to be selected in total.

**Comment by LIUkhan** [comment]
Thx for your kind reply!
